-- =============================================================================
-- IT CAPITAL & REVENUE BUDGET MONITORING — FULL ORACLE SCHEMA
-- Schema/user name: IT_CAPITAL
-- Amounts: Rs. in Crore → NUMBER(20,2)
-- Month: name (April, May, ... March) — Indian FY Apr–Mar
-- Soft delete: IS_ACTIVE 'Y'/'N' (no hard delete for masters)
--
-- EXTERNAL (not in this Oracle schema — same pattern as Personal/SCV):
--   SQL Server org DB table STAFF_DETAILS (EMP_ID, EMP_NAME, DEPTID, EMP_DESGN_DESC, …)
--   → PF/EMP lookup for name + designation after login / when adding team
--   AD API validateDomainUser → JWT (app layer, like Personal)
-- =============================================================================

ALTER SESSION SET CURRENT_SCHEMA = IT_CAPITAL;

-- -----------------------------------------------------------------------------
-- 1. DEPARTMENT
-- -----------------------------------------------------------------------------
CREATE TABLE DEPARTMENT (
    DEPT_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DEPT_CODE         VARCHAR2(50),
    DEPT_NAME         VARCHAR2(200) NOT NULL,
    HAS_REVENUE       CHAR(1) DEFAULT 'N' NOT NULL,  -- 'Y' only for DIT (client)
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT CK_DEPT_HAS_REV CHECK (HAS_REVENUE IN ('Y','N')),
    CONSTRAINT CK_DEPT_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

CREATE UNIQUE INDEX UK_DEPT_NAME ON DEPARTMENT (DEPT_NAME);

-- -----------------------------------------------------------------------------
-- 2. SECTION  (belongs to department)
-- -----------------------------------------------------------------------------
CREATE TABLE SECTION (
    SECTION_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DEPT_ID           NUMBER NOT NULL,
    SECTION_CODE      VARCHAR2(50),
    SECTION_NAME      VARCHAR2(300) NOT NULL,
    DESCRIPTION       VARCHAR2(500),
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_SECTION_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID),
    CONSTRAINT CK_SECTION_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

CREATE INDEX IX_SECTION_DEPT ON SECTION (DEPT_ID);
CREATE UNIQUE INDEX UK_SECTION_DEPT_NAME ON SECTION (DEPT_ID, SECTION_NAME);

-- -----------------------------------------------------------------------------
-- 3. DEPARTMENT_AUTHORITY
--     New convo: one CTO per department; CGM one/more; multiple GM; multiple DGM.
--     Section not required for AGM and above (they manage CMs/sections).
--     REPORTS_TO_PF = who this person reports to (for reporting-chain display;
--     needed when multiple GMs/DGMs exist — role order alone is not enough).
-- -----------------------------------------------------------------------------
CREATE TABLE DEPARTMENT_AUTHORITY (
    AUTHORITY_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DEPT_ID           NUMBER NOT NULL,
    AUTHORITY_ROLE    VARCHAR2(20) NOT NULL,  -- CTO / CGM / GM / DGM / AGM
    PF_NO             VARCHAR2(20) NOT NULL,
    PERSON_NAME       VARCHAR2(200),          -- snapshot from STAFF_DETAILS at save
    DESIGNATION       VARCHAR2(100),          -- snapshot from STAFF_DETAILS at save
    REPORTS_TO_PF     VARCHAR2(20),           -- PF of manager in chain (nullable)
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_DAUTH_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID),
    CONSTRAINT CK_DAUTH_ROLE CHECK (AUTHORITY_ROLE IN ('CTO','CGM','GM','DGM','AGM')),
    CONSTRAINT CK_DAUTH_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT UK_DAUTH_DEPT_ROLE_PF UNIQUE (DEPT_ID, AUTHORITY_ROLE, PF_NO)
);

CREATE INDEX IX_DAUTH_PF ON DEPARTMENT_AUTHORITY (PF_NO);
CREATE INDEX IX_DAUTH_REPORTS ON DEPARTMENT_AUTHORITY (REPORTS_TO_PF);

-- -----------------------------------------------------------------------------
-- 4. SECTION_AUTHORITY
--     New convo + manager: CM (and team lead) at section level.
--     CM can have many sections = many rows with same CM PF.
--     Multi same-role allowed via UK on (SECTION_ID, ROLE, PF) not (SECTION_ID, ROLE).
-- -----------------------------------------------------------------------------
CREATE TABLE SECTION_AUTHORITY (
    AUTHORITY_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SECTION_ID        NUMBER NOT NULL,
    AUTHORITY_ROLE    VARCHAR2(20) NOT NULL,  -- CM / TEAM_LEAD
    PF_NO             VARCHAR2(20) NOT NULL,
    PERSON_NAME       VARCHAR2(200),
    DESIGNATION       VARCHAR2(100),
    REPORTS_TO_PF     VARCHAR2(20),
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_SAUTH_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION (SECTION_ID),
    CONSTRAINT CK_SAUTH_ROLE CHECK (AUTHORITY_ROLE IN ('CM','TEAM_LEAD')),
    CONSTRAINT CK_SAUTH_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT UK_SAUTH_SEC_ROLE_PF UNIQUE (SECTION_ID, AUTHORITY_ROLE, PF_NO)
);

CREATE INDEX IX_SAUTH_PF ON SECTION_AUTHORITY (PF_NO);
CREATE INDEX IX_SAUTH_REPORTS ON SECTION_AUTHORITY (REPORTS_TO_PF);

-- -----------------------------------------------------------------------------
-- 5. SECTION_TEAM_MEMBER  (team under section, PF-wise, soft delete)
--     Name/designation filled from SQL Server STAFF_DETAILS lookup (Personal pattern)
-- -----------------------------------------------------------------------------
CREATE TABLE SECTION_TEAM_MEMBER (
    MEMBER_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SECTION_ID        NUMBER NOT NULL,
    PF_NO             VARCHAR2(20) NOT NULL,
    PERSON_NAME       VARCHAR2(200),
    DESIGNATION       VARCHAR2(100),
    REPORTS_TO_PF     VARCHAR2(20),           -- usually CM / TEAM_LEAD PF
    MEMBER_ROLE       VARCHAR2(100),          -- e.g. Assistant Manager (free text)
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_MEMBER_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION (SECTION_ID),
    CONSTRAINT CK_MEMBER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT UK_MEMBER_SECTION_PF UNIQUE (SECTION_ID, PF_NO)
);

CREATE INDEX IX_MEMBER_PF ON SECTION_TEAM_MEMBER (PF_NO);

-- -----------------------------------------------------------------------------
-- 6. PROJECT  (Capital only — under section)
-- -----------------------------------------------------------------------------
CREATE TABLE PROJECT (
    PROJECT_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SECTION_ID        NUMBER NOT NULL,
    PROJECT_CODE      VARCHAR2(50),
    PROJECT_NAME      VARCHAR2(500) NOT NULL,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_PROJECT_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION (SECTION_ID),
    CONSTRAINT CK_PROJECT_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

CREATE INDEX IX_PROJECT_SECTION ON PROJECT (SECTION_ID);
CREATE UNIQUE INDEX UK_PROJECT_SECTION_NAME ON PROJECT (SECTION_ID, PROJECT_NAME);

-- -----------------------------------------------------------------------------
-- 7. PROJECT_ASSIGNMENT
--     New convo: projects allocated to particular person; AM can have multiple projects.
--     CM assigns projects to people.
-- -----------------------------------------------------------------------------
CREATE TABLE PROJECT_ASSIGNMENT (
    ASSIGN_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PROJECT_ID        NUMBER NOT NULL,
    PF_NO             VARCHAR2(20) NOT NULL,
    PERSON_NAME       VARCHAR2(200),
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_PASSIGN_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT CK_PASSIGN_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT UK_PASSIGN_PROJ_PF UNIQUE (PROJECT_ID, PF_NO)
);

CREATE INDEX IX_PASSIGN_PF ON PROJECT_ASSIGNMENT (PF_NO);

-- -----------------------------------------------------------------------------
-- 8. PROJECT_FY_ALLOTMENT  (Capital master — per FY)
--     TOTAL_ALLOTTED = spillover + fresh — app-calculated only
-- -----------------------------------------------------------------------------
CREATE TABLE PROJECT_FY_ALLOTMENT (
    ALLOTMENT_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PROJECT_ID           NUMBER NOT NULL,
    FINANCIAL_YEAR       VARCHAR2(20) NOT NULL,
    SPILLOVER_ALLOTTED   NUMBER(20,2) DEFAULT 0 NOT NULL,
    FRESH_ALLOTTED       NUMBER(20,2) DEFAULT 0 NOT NULL,
    TOTAL_ALLOTTED       NUMBER(20,2) DEFAULT 0 NOT NULL,
    IS_ACTIVE            CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    CREATED_BY           VARCHAR2(100),
    UPDATED_BY           VARCHAR2(100),
    CONSTRAINT FK_PALL_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT CK_PALL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT UK_PALL_PROJ_FY UNIQUE (PROJECT_ID, FINANCIAL_YEAR)
);

-- -----------------------------------------------------------------------------
-- 9. CAPITAL_MONTHLY_ENTRY
--     UK (PROJECT_ID, FINANCIAL_YEAR, ENTRY_MONTH) = only ONE row per project/FY/month.
--     New convo: if budget already written for that project, others cannot write.
--     App: first submit wins; later users see read-only. DB unique enforces one entry.
-- -----------------------------------------------------------------------------
CREATE TABLE CAPITAL_MONTHLY_ENTRY (
    ENTRY_ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PROJECT_ID              NUMBER NOT NULL,
    FINANCIAL_YEAR          VARCHAR2(20) NOT NULL,
    ENTRY_MONTH             VARCHAR2(20) NOT NULL,
    ACTUAL_SPILLOVER        NUMBER(20,2) DEFAULT 0 NOT NULL,
    ACTUAL_FRESH            NUMBER(20,2) DEFAULT 0 NOT NULL,
    ACTUAL_TOTAL            NUMBER(20,2) DEFAULT 0 NOT NULL,
    EST_SPILLOVER_NEXT      NUMBER(20,2) DEFAULT 0 NOT NULL,
    EST_FRESH_NEXT          NUMBER(20,2) DEFAULT 0 NOT NULL,
    EST_TOTAL_NEXT          NUMBER(20,2) DEFAULT 0 NOT NULL,
    JUSTIFICATION_TEXT      VARCHAR2(4000),
    ENTRY_STATUS            VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,  -- DRAFT / SUBMITTED
    SUBMITTED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SUBMITTED_BY_PF         VARCHAR2(20),  -- who wrote (write-lock owner)
    IS_ACTIVE               CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP,
    CREATED_BY              VARCHAR2(100),
    UPDATED_BY              VARCHAR2(100),
    CONSTRAINT FK_CAP_ENTRY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT CK_CAP_ENTRY_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CK_CAP_ENTRY_STATUS CHECK (ENTRY_STATUS IN ('DRAFT','SUBMITTED')),
    CONSTRAINT CK_CAP_ENTRY_MONTH CHECK (ENTRY_MONTH IN (
        'April','May','June','July','August','September',
        'October','November','December','January','February','March')),
    CONSTRAINT UK_CAP_ENTRY UNIQUE (PROJECT_ID, FINANCIAL_YEAR, ENTRY_MONTH)
);

CREATE INDEX IX_CAP_ENTRY_FY_MON ON CAPITAL_MONTHLY_ENTRY (FINANCIAL_YEAR, ENTRY_MONTH);
CREATE INDEX IX_CAP_ENTRY_BY ON CAPITAL_MONTHLY_ENTRY (SUBMITTED_BY_PF);

-- -----------------------------------------------------------------------------
-- 10. REVENUE_HEAD  (18 fixed heads from master sheet)
-- -----------------------------------------------------------------------------
CREATE TABLE REVENUE_HEAD (
    HEAD_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HEAD_CODE         VARCHAR2(50) NOT NULL,
    HEAD_NAME         VARCHAR2(100) NOT NULL,
    DISPLAY_ORDER     NUMBER NOT NULL,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT UK_HEAD_CODE UNIQUE (HEAD_CODE),
    CONSTRAINT UK_HEAD_NAME UNIQUE (HEAD_NAME),
    CONSTRAINT CK_HEAD_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('RENT', 'RENT', 1);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('TAXES', 'TAXES', 2);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('ELECTRICITY_CHARGES', 'ELECTRICITY CHARGES', 3);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('PRINTING_STATIONERY', 'PRINTING & STATIONERY', 4);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('POSTAGE', 'POSTAGE', 5);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('BANDWIDTH', 'BANDWIDTH', 6);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('SMS_EMAIL_WHATSAPP', 'SMS/EMAIL/WHATSAPP', 7);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('AMC', 'AMC', 8);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('ATS', 'ATS', 9);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('M_R', 'M&R', 10);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('TRAINING', 'TRAINING', 11);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('PETTY_OFF', 'PETTY OFF', 12);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('AUDIT', 'AUDIT', 13);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('FMS', 'FMS', 14);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('NW_RENT', 'NW RENT', 15);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('PROF_FEES', 'PROF FEES', 16);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('INSURANCE', 'INSURANCE', 17);
INSERT INTO REVENUE_HEAD (HEAD_CODE, HEAD_NAME, DISPLAY_ORDER) VALUES ('MISC', 'MISC', 18);
COMMIT;

-- -----------------------------------------------------------------------------
-- 11. SECTION_FY_REVENUE_ALLOTMENT
-- -----------------------------------------------------------------------------
CREATE TABLE SECTION_FY_REVENUE_ALLOTMENT (
    ALLOTMENT_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SECTION_ID        NUMBER NOT NULL,
    FINANCIAL_YEAR    VARCHAR2(20) NOT NULL,
    TOTAL_ALLOTTED    NUMBER(20,2) DEFAULT 0 NOT NULL,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_RALL_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION (SECTION_ID),
    CONSTRAINT CK_RALL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT UK_RALL_SEC_FY UNIQUE (SECTION_ID, FINANCIAL_YEAR)
);

-- -----------------------------------------------------------------------------
-- 12. REVENUE_MONTHLY_ENTRY  (header — DIT section, no project)
-- -----------------------------------------------------------------------------
CREATE TABLE REVENUE_MONTHLY_ENTRY (
    ENTRY_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SECTION_ID        NUMBER NOT NULL,
    FINANCIAL_YEAR    VARCHAR2(20) NOT NULL,
    ENTRY_MONTH       VARCHAR2(20) NOT NULL,
    ENTRY_STATUS      VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,
    SUBMITTED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SUBMITTED_BY_PF   VARCHAR2(20),
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_REV_ENTRY_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION (SECTION_ID),
    CONSTRAINT CK_REV_ENTRY_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CK_REV_ENTRY_STATUS CHECK (ENTRY_STATUS IN ('DRAFT','SUBMITTED')),
    CONSTRAINT CK_REV_ENTRY_MONTH CHECK (ENTRY_MONTH IN (
        'April','May','June','July','August','September',
        'October','November','December','January','February','March')),
    CONSTRAINT UK_REV_ENTRY UNIQUE (SECTION_ID, FINANCIAL_YEAR, ENTRY_MONTH)
);

CREATE INDEX IX_REV_ENTRY_FY_MON ON REVENUE_MONTHLY_ENTRY (FINANCIAL_YEAR, ENTRY_MONTH);

-- -----------------------------------------------------------------------------
-- 13. REVENUE_MONTHLY_ENTRY_LINE
-- -----------------------------------------------------------------------------
CREATE TABLE REVENUE_MONTHLY_ENTRY_LINE (
    LINE_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ENTRY_ID          NUMBER NOT NULL,
    HEAD_ID           NUMBER NOT NULL,
    AMOUNT            NUMBER(20,2) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_REV_LINE_ENTRY FOREIGN KEY (ENTRY_ID) REFERENCES REVENUE_MONTHLY_ENTRY (ENTRY_ID),
    CONSTRAINT FK_REV_LINE_HEAD FOREIGN KEY (HEAD_ID) REFERENCES REVENUE_HEAD (HEAD_ID),
    CONSTRAINT UK_REV_LINE UNIQUE (ENTRY_ID, HEAD_ID)
);

CREATE INDEX IX_REV_LINE_HEAD ON REVENUE_MONTHLY_ENTRY_LINE (HEAD_ID);

-- -----------------------------------------------------------------------------
-- 14. APP_USER
--     Production login (Personal/SCV pattern + your confirm):
--       PF (user_id) + AD password + captcha → AD validateDomainUser → JWT
--     Staff name/dept from SQL Server STAFF_DETAILS (not stored as employee master here).
--     One person → one department (new convo).
-- -----------------------------------------------------------------------------
CREATE TABLE APP_USER (
    USER_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PF_NO             VARCHAR2(20) NOT NULL,   -- same as AD user_id / EMP_ID
    USER_NAME         VARCHAR2(200),
    DESIGNATION       VARCHAR2(100),
    DEPT_ID           NUMBER,                  -- auto dept; one person one dept
    ROLE_CODE         VARCHAR2(20) NOT NULL,  -- ADMIN / CM / MEMBER
    AD_LOGIN_ID       VARCHAR2(200),          -- AD login id if different from PF
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT UK_USER_PF UNIQUE (PF_NO),
    CONSTRAINT FK_USER_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID),
    CONSTRAINT CK_USER_ROLE CHECK (ROLE_CODE IN ('ADMIN','CM','MEMBER')),
    CONSTRAINT CK_USER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

-- -----------------------------------------------------------------------------
-- 15. USER_SECTION_MAP  (CM multi-section — sections assigned, not free-change)
-- -----------------------------------------------------------------------------
CREATE TABLE USER_SECTION_MAP (
    MAP_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID           NUMBER NOT NULL,
    SECTION_ID        NUMBER NOT NULL,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_USM_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT FK_USM_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION (SECTION_ID),
    CONSTRAINT CK_USM_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT UK_USM UNIQUE (USER_ID, SECTION_ID)
);

-- -----------------------------------------------------------------------------
-- 16. USER_TOKEN  (Personal/SCV session pattern — single active JWT per user)
-- -----------------------------------------------------------------------------
CREATE TABLE USER_TOKEN (
    REF_NO            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERID            VARCHAR2(60) NOT NULL,   -- PF / encrypted id as in Personal
    USERNAME          NVARCHAR2(150),
    LASTTOKEN         NVARCHAR2(800),
    HASH_TOKEN        NVARCHAR2(200),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_USER_TOKEN_USERID ON USER_TOKEN (USERID);

-- -----------------------------------------------------------------------------
-- 17. LOGIN_CAPTCHA_QUESTION
--     Personal uses SQL Server login_question; we keep captcha in our Oracle app DB
--     so login works the same way (question + answer) without depending on SCV tables.
-- -----------------------------------------------------------------------------
CREATE TABLE LOGIN_CAPTCHA_QUESTION (
    Q_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    QUESTION_TEXT     VARCHAR2(500) NOT NULL,
    ANSWER_TEXT       VARCHAR2(200) NOT NULL,
    IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT CK_CAPTCHA_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

-- =============================================================================
-- END OF SCHEMA
-- Oracle tables: 17
-- External: SQL Server STAFF_DETAILS (Personal OrganisationsDbContext pattern)
-- Login app flow: PF + AD password + captcha → AD API → JWT → USER_TOKEN
-- =============================================================================
