-- =============================================================================
-- ALTER: Project / Section Maker-Checker (Priyadarshini 30-Jul-2026)
-- Run once on existing Oracle schema (safe if columns already exist — skip errors).
-- =============================================================================
-- Rules:
--   DIT capital  → PROJECT.MAKER_PF / PROJECT.CHECKER_PF (project-wise)
--   DIT revenue  → SECTION.MAKER_PF / SECTION.CHECKER_PF (section-wise)
--   Other depts  → DEPARTMENT.MAKER_PF / DEPARTMENT.CHECKER_PF (department-wise)
-- =============================================================================

SET DEFINE OFF;

-- PROJECT columns
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PROJECT ADD (MAKER_PF VARCHAR2(20))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF; -- column already exists
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PROJECT ADD (CHECKER_PF VARCHAR2(20))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- SECTION columns
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SECTION ADD (MAKER_PF VARCHAR2(20))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SECTION ADD (CHECKER_PF VARCHAR2(20))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

CREATE INDEX IX_PROJECT_CHECKER ON PROJECT (CHECKER_PF);
CREATE INDEX IX_PROJECT_MAKER ON PROJECT (MAKER_PF);
CREATE INDEX IX_SECTION_CHECKER ON SECTION (CHECKER_PF);
CREATE INDEX IX_SECTION_MAKER ON SECTION (MAKER_PF);

-- Backfill DIT projects from department Maker/Checker (so existing checkers keep seeing work)
UPDATE PROJECT p
SET (MAKER_PF, CHECKER_PF) = (
    SELECT d.MAKER_PF, d.CHECKER_PF
    FROM SECTION s
    JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
    WHERE s.SECTION_ID = p.SECTION_ID
      AND UPPER(TRIM(d.DEPT_CODE)) = 'DIT'
)
WHERE EXISTS (
    SELECT 1 FROM SECTION s
    JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
    WHERE s.SECTION_ID = p.SECTION_ID
      AND UPPER(TRIM(d.DEPT_CODE)) = 'DIT'
)
AND p.MAKER_PF IS NULL
AND p.CHECKER_PF IS NULL;

-- Backfill DIT revenue sections from department Maker/Checker
UPDATE SECTION s
SET (MAKER_PF, CHECKER_PF) = (
    SELECT d.MAKER_PF, d.CHECKER_PF
    FROM DEPARTMENT d
    WHERE d.DEPT_ID = s.DEPT_ID
      AND UPPER(TRIM(d.DEPT_CODE)) = 'DIT'
      AND d.HAS_REVENUE = 'Y'
)
WHERE EXISTS (
    SELECT 1 FROM DEPARTMENT d
    WHERE d.DEPT_ID = s.DEPT_ID
      AND UPPER(TRIM(d.DEPT_CODE)) = 'DIT'
      AND d.HAS_REVENUE = 'Y'
)
AND s.MAKER_PF IS NULL
AND s.CHECKER_PF IS NULL;

COMMIT;

-- Verify
SELECT p.PROJECT_NAME, p.MAKER_PF, p.CHECKER_PF, d.DEPT_CODE
FROM PROJECT p
JOIN SECTION s ON s.SECTION_ID = p.SECTION_ID
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE p.IS_ACTIVE = 'Y'
ORDER BY d.DEPT_CODE, p.PROJECT_NAME;

SELECT s.SECTION_NAME, s.MAKER_PF, s.CHECKER_PF, d.DEPT_CODE
FROM SECTION s
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE s.IS_ACTIVE = 'Y' AND d.HAS_REVENUE = 'Y'
ORDER BY s.SECTION_NAME;
