-- Fix: Revenue allotment for all DIT sections (Treasury / Networking / etc. were missing → UI showed 0.00).
-- Run once against IT_BUDGET_MONITORING_PORTAL if schema was already seeded with PCI-only allotment.

MERGE INTO SECTION_FY_REVENUE_ALLOTMENT t
USING (
    SELECT s.SECTION_ID, '2026-27' AS FINANCIAL_YEAR, 7.00 AS TOTAL_ALLOTTED
    FROM SECTION s
    JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
    WHERE d.DEPT_CODE = 'DIT' AND s.IS_ACTIVE = 'Y'
) s
ON (t.SECTION_ID = s.SECTION_ID AND t.FINANCIAL_YEAR = s.FINANCIAL_YEAR)
WHEN MATCHED THEN
    UPDATE SET t.TOTAL_ALLOTTED = s.TOTAL_ALLOTTED, t.IS_ACTIVE = 'Y'
WHEN NOT MATCHED THEN
    INSERT (SECTION_ID, FINANCIAL_YEAR, TOTAL_ALLOTTED, CREATED_BY)
    VALUES (s.SECTION_ID, s.FINANCIAL_YEAR, s.TOTAL_ALLOTTED, 'SAMPLE');

COMMIT;
