-- =============================================================================
-- FIX: Checker 600221 sees 0 Capital / Revenue pending (and 0 submissions)
-- Run in SQL Developer connected as the app Oracle user. SET DEFINE OFF first.
-- =============================================================================
-- Root causes this script addresses:
--   1) DEPARTMENT.CHECKER_PF / PROJECT.CHECKER_PF / SECTION.CHECKER_PF not 600221
--   2) APP_USER missing or inactive for 600221
--   3) No PENDING July (or current) capital/revenue rows
--   4) Soft-deleted departments / projects
-- =============================================================================

SET DEFINE OFF;

-- ---------- 1) DIAGNOSE (read-only) ----------
SELECT 'DEPT' AS SRC, DEPT_CODE, MAKER_PF, CHECKER_PF, IS_ACTIVE
FROM DEPARTMENT
ORDER BY DEPT_ID;

SELECT 'APP_USER' AS SRC, PF_NO, ROLE_CODE, DEPT_ID, IS_ACTIVE
FROM APP_USER
WHERE PF_NO IN ('600110','600221','600222','100001');

SELECT e.ENTRY_ID, e.ENTRY_MONTH, e.ENTRY_STATUS, e.SUBMITTED_BY_PF,
       p.PROJECT_NAME, p.CHECKER_PF AS PROJECT_CHECKER, d.CHECKER_PF AS DEPT_CHECKER, d.IS_ACTIVE AS DEPT_ACTIVE
FROM CAPITAL_MONTHLY_ENTRY e
JOIN PROJECT p ON p.PROJECT_ID = e.PROJECT_ID
JOIN SECTION s ON s.SECTION_ID = p.SECTION_ID
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE e.IS_ACTIVE = 'Y'
ORDER BY e.SUBMITTED_AT DESC NULLS LAST;

SELECT e.ENTRY_ID, e.ENTRY_MONTH, e.ENTRY_STATUS, e.SUBMITTED_BY_PF,
       s.SECTION_NAME, s.CHECKER_PF AS SECTION_CHECKER, d.CHECKER_PF AS DEPT_CHECKER
FROM REVENUE_MONTHLY_ENTRY e
JOIN SECTION s ON s.SECTION_ID = e.SECTION_ID
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE e.IS_ACTIVE = 'Y'
ORDER BY e.SUBMITTED_AT DESC NULLS LAST;

-- ---------- 2) ENSURE CHECKER USER ----------
MERGE INTO APP_USER u
USING (
  SELECT '600221' AS PF_NO,
         'SAMPLE Checker' AS USER_NAME,
         'Checker' AS DESIGNATION,
         (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DIT' AND IS_ACTIVE = 'Y' AND ROWNUM = 1) AS DEPT_ID,
         'CHECKER' AS ROLE_CODE,
         '600221' AS AD_LOGIN_ID
  FROM DUAL
) src
ON (u.PF_NO = src.PF_NO)
WHEN MATCHED THEN UPDATE SET
  u.IS_ACTIVE = 'Y',
  u.ROLE_CODE = 'CHECKER',
  u.DEPT_ID = NVL(src.DEPT_ID, u.DEPT_ID),
  u.UPDATED_AT = SYSTIMESTAMP,
  u.UPDATED_BY = 'FIX_SCRIPT'
WHEN NOT MATCHED THEN INSERT (PF_NO, USER_NAME, DESIGNATION, DEPT_ID, ROLE_CODE, AD_LOGIN_ID, IS_ACTIVE, CREATED_BY)
VALUES (src.PF_NO, src.USER_NAME, src.DESIGNATION, src.DEPT_ID, src.ROLE_CODE, src.AD_LOGIN_ID, 'Y', 'FIX_SCRIPT');

-- Maker (needed for submissions)
MERGE INTO APP_USER u
USING (
  SELECT '600110' AS PF_NO,
         'SAMPLE Maker' AS USER_NAME,
         'Maker' AS DESIGNATION,
         (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DIT' AND IS_ACTIVE = 'Y' AND ROWNUM = 1) AS DEPT_ID,
         'MAKER' AS ROLE_CODE,
         '600110' AS AD_LOGIN_ID
  FROM DUAL
) src
ON (u.PF_NO = src.PF_NO)
WHEN MATCHED THEN UPDATE SET u.IS_ACTIVE = 'Y', u.ROLE_CODE = 'MAKER', u.UPDATED_BY = 'FIX_SCRIPT'
WHEN NOT MATCHED THEN INSERT (PF_NO, USER_NAME, DESIGNATION, DEPT_ID, ROLE_CODE, AD_LOGIN_ID, IS_ACTIVE, CREATED_BY)
VALUES (src.PF_NO, src.USER_NAME, src.DESIGNATION, src.DEPT_ID, src.ROLE_CODE, src.AD_LOGIN_ID, 'Y', 'FIX_SCRIPT');

-- ---------- 3) POINT DIT CHECKER TO 600221 ----------
UPDATE DEPARTMENT
SET CHECKER_PF = '600221',
    MAKER_PF = NVL(MAKER_PF, '600110'),
    IS_ACTIVE = 'Y',
    UPDATED_AT = SYSTIMESTAMP,
    UPDATED_BY = 'FIX_SCRIPT'
WHERE DEPT_CODE = 'DIT';

-- If ALTER_PROJECT_SECTION_MAKER_CHECKER.sql was run, also set project/section
BEGIN
  EXECUTE IMMEDIATE q'[
    UPDATE PROJECT p
    SET CHECKER_PF = ''600221'',
        MAKER_PF = NVL(MAKER_PF, ''600110''),
        UPDATED_AT = SYSTIMESTAMP,
        UPDATED_BY = ''FIX_SCRIPT''
    WHERE EXISTS (
      SELECT 1 FROM SECTION s
      JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
      WHERE s.SECTION_ID = p.SECTION_ID AND d.DEPT_CODE = ''DIT''
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -904 THEN NULL; -- column not yet added
    ELSE RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    UPDATE SECTION s
    SET CHECKER_PF = ''600221'',
        MAKER_PF = NVL(MAKER_PF, ''600110''),
        UPDATED_AT = SYSTIMESTAMP,
        UPDATED_BY = ''FIX_SCRIPT''
    WHERE EXISTS (
      SELECT 1 FROM DEPARTMENT d
      WHERE d.DEPT_ID = s.DEPT_ID AND d.DEPT_CODE = ''DIT'' AND d.HAS_REVENUE = ''Y''
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -904 THEN NULL;
    ELSE RAISE;
    END IF;
END;
/

-- ---------- 4) ENSURE JULY PENDING CAPITAL (WAN Refreshed) ----------
MERGE INTO CAPITAL_MONTHLY_ENTRY e
USING (
  SELECT p.PROJECT_ID,
         '2026-27' AS FINANCIAL_YEAR,
         'July' AS ENTRY_MONTH
  FROM PROJECT p
  WHERE p.PROJECT_NAME = 'WAN Refreshed' AND p.IS_ACTIVE = 'Y' AND ROWNUM = 1
) src
ON (e.PROJECT_ID = src.PROJECT_ID
    AND e.FINANCIAL_YEAR = src.FINANCIAL_YEAR
    AND e.ENTRY_MONTH = src.ENTRY_MONTH
    AND e.IS_ACTIVE = 'Y')
WHEN MATCHED THEN UPDATE SET
  e.ENTRY_STATUS = 'PENDING',
  e.ACTUAL_SPILLOVER = NVL(NULLIF(e.ACTUAL_SPILLOVER, 0), 0.40),
  e.ACTUAL_FRESH = NVL(NULLIF(e.ACTUAL_FRESH, 0), 0.20),
  e.ACTUAL_TOTAL = NVL(NULLIF(e.ACTUAL_TOTAL, 0), 0.60),
  e.EST_SPILLOVER_NEXT = NVL(e.EST_SPILLOVER_NEXT, 0.30),
  e.EST_FRESH_NEXT = NVL(e.EST_FRESH_NEXT, 0.10),
  e.EST_TOTAL_NEXT = NVL(e.EST_TOTAL_NEXT, 0.40),
  e.JUSTIFICATION_TEXT = NVL(e.JUSTIFICATION_TEXT, 'FIX_SCRIPT pending July capital'),
  e.SUBMITTED_BY_PF = NVL(e.SUBMITTED_BY_PF, '600110'),
  e.SUBMITTED_AT = NVL(e.SUBMITTED_AT, SYSTIMESTAMP),
  e.CHECKED_AT = NULL,
  e.CHECKED_BY_PF = NULL,
  e.CHECKER_REMARK = NULL,
  e.UPDATED_AT = SYSTIMESTAMP,
  e.UPDATED_BY = 'FIX_SCRIPT'
WHEN NOT MATCHED THEN INSERT (
  PROJECT_ID, FINANCIAL_YEAR, ENTRY_MONTH,
  ACTUAL_SPILLOVER, ACTUAL_FRESH, ACTUAL_TOTAL,
  EST_SPILLOVER_NEXT, EST_FRESH_NEXT, EST_TOTAL_NEXT,
  JUSTIFICATION_TEXT, ENTRY_STATUS, SUBMITTED_BY_PF, SUBMITTED_AT, IS_ACTIVE, CREATED_BY)
VALUES (
  src.PROJECT_ID, src.FINANCIAL_YEAR, src.ENTRY_MONTH,
  0.40, 0.20, 0.60,
  0.30, 0.10, 0.40,
  'FIX_SCRIPT pending July capital', 'PENDING', '600110', SYSTIMESTAMP, 'Y', 'FIX_SCRIPT');

-- Ensure June APPROVED exists (previous-month panel)
MERGE INTO CAPITAL_MONTHLY_ENTRY e
USING (
  SELECT p.PROJECT_ID, '2026-27' AS FINANCIAL_YEAR, 'June' AS ENTRY_MONTH
  FROM PROJECT p WHERE p.PROJECT_NAME = 'WAN Refreshed' AND p.IS_ACTIVE = 'Y' AND ROWNUM = 1
) src
ON (e.PROJECT_ID = src.PROJECT_ID AND e.FINANCIAL_YEAR = src.FINANCIAL_YEAR
    AND e.ENTRY_MONTH = src.ENTRY_MONTH AND e.IS_ACTIVE = 'Y')
WHEN NOT MATCHED THEN INSERT (
  PROJECT_ID, FINANCIAL_YEAR, ENTRY_MONTH,
  ACTUAL_SPILLOVER, ACTUAL_FRESH, ACTUAL_TOTAL,
  EST_SPILLOVER_NEXT, EST_FRESH_NEXT, EST_TOTAL_NEXT,
  JUSTIFICATION_TEXT, ENTRY_STATUS, SUBMITTED_BY_PF, CHECKED_BY_PF, CHECKED_AT, IS_ACTIVE, CREATED_BY)
VALUES (
  src.PROJECT_ID, src.FINANCIAL_YEAR, src.ENTRY_MONTH,
  1.00, 0.50, 1.50, 0.75, 0.00, 0.75,
  'FIX_SCRIPT approved June capital', 'APPROVED', '600110', '600221', SYSTIMESTAMP, 'Y', 'FIX_SCRIPT');

-- ---------- 5) ENSURE JULY PENDING REVENUE (Private Cloud Infrastructure) ----------
MERGE INTO REVENUE_MONTHLY_ENTRY e
USING (
  SELECT s.SECTION_ID, '2026-27' AS FINANCIAL_YEAR, 'July' AS ENTRY_MONTH
  FROM SECTION s WHERE s.SECTION_NAME = 'Private Cloud Infrastructure' AND s.IS_ACTIVE = 'Y' AND ROWNUM = 1
) src
ON (e.SECTION_ID = src.SECTION_ID AND e.FINANCIAL_YEAR = src.FINANCIAL_YEAR
    AND e.ENTRY_MONTH = src.ENTRY_MONTH AND e.IS_ACTIVE = 'Y')
WHEN MATCHED THEN UPDATE SET
  e.ENTRY_STATUS = 'PENDING',
  e.JUSTIFICATION_TEXT = NVL(e.JUSTIFICATION_TEXT, 'FIX_SCRIPT pending July revenue'),
  e.SUBMITTED_BY_PF = NVL(e.SUBMITTED_BY_PF, '600110'),
  e.SUBMITTED_AT = NVL(e.SUBMITTED_AT, SYSTIMESTAMP),
  e.CHECKED_AT = NULL,
  e.CHECKED_BY_PF = NULL,
  e.CHECKER_REMARK = NULL,
  e.UPDATED_BY = 'FIX_SCRIPT'
WHEN NOT MATCHED THEN INSERT (
  SECTION_ID, FINANCIAL_YEAR, ENTRY_MONTH, JUSTIFICATION_TEXT,
  ENTRY_STATUS, SUBMITTED_BY_PF, SUBMITTED_AT, IS_ACTIVE, CREATED_BY)
VALUES (
  src.SECTION_ID, src.FINANCIAL_YEAR, src.ENTRY_MONTH, 'FIX_SCRIPT pending July revenue',
  'PENDING', '600110', SYSTIMESTAMP, 'Y', 'FIX_SCRIPT');

-- Seed lines for July revenue if missing
INSERT INTO REVENUE_MONTHLY_ENTRY_LINE (ENTRY_ID, HEAD_ID, AMOUNT)
SELECT e.ENTRY_ID, h.HEAD_ID,
       CASE h.HEAD_CODE
            WHEN 'FMS' THEN 0.08
            WHEN 'AMC' THEN 0.12
            WHEN 'RENT' THEN 0.20
            WHEN 'BANDWIDTH' THEN 0.05
            ELSE 0
       END
FROM REVENUE_MONTHLY_ENTRY e
JOIN SECTION s ON s.SECTION_ID = e.SECTION_ID AND s.SECTION_NAME = 'Private Cloud Infrastructure'
CROSS JOIN REVENUE_HEAD h
WHERE e.FINANCIAL_YEAR = '2026-27' AND e.ENTRY_MONTH = 'July' AND e.IS_ACTIVE = 'Y'
  AND NOT EXISTS (
      SELECT 1 FROM REVENUE_MONTHLY_ENTRY_LINE l WHERE l.ENTRY_ID = e.ENTRY_ID AND l.HEAD_ID = h.HEAD_ID
  );

COMMIT;

-- ---------- 6) VERIFY what Checker 600221 should see ----------
SELECT 'CAPITAL_PENDING' AS Q, COUNT(*) AS CNT
FROM CAPITAL_MONTHLY_ENTRY e
JOIN PROJECT p ON p.PROJECT_ID = e.PROJECT_ID
JOIN SECTION s ON s.SECTION_ID = p.SECTION_ID
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE e.IS_ACTIVE = 'Y' AND e.ENTRY_STATUS = 'PENDING'
  AND d.IS_ACTIVE = 'Y'
  AND (
        TRIM(d.CHECKER_PF) = '600221'
     OR (EXISTS (
           SELECT 1 FROM USER_TAB_COLUMNS c
           WHERE c.TABLE_NAME = 'PROJECT' AND c.COLUMN_NAME = 'CHECKER_PF'
         ) AND TRIM(p.CHECKER_PF) = '600221')
      );

SELECT 'REVENUE_PENDING' AS Q, COUNT(*) AS CNT
FROM REVENUE_MONTHLY_ENTRY e
JOIN SECTION s ON s.SECTION_ID = e.SECTION_ID
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE e.IS_ACTIVE = 'Y' AND e.ENTRY_STATUS = 'PENDING'
  AND d.IS_ACTIVE = 'Y'
  AND (
        TRIM(d.CHECKER_PF) = '600221'
     OR TRIM(s.CHECKER_PF) = '600221'
      );
