-- =============================================================================
-- SEED / ASSIGN Maker + Checker PFs (APP_USER + DEPARTMENT / PROJECT / SECTION)
-- Run after ALTER_PROJECT_SECTION_MAKER_CHECKER.sql
-- Customize PF numbers below if needed.
-- =============================================================================
-- Roles:
--   DIT Capital  → PROJECT.MAKER_PF / PROJECT.CHECKER_PF
--   DIT Revenue  → SECTION.MAKER_PF / SECTION.CHECKER_PF
--   Other depts  → DEPARTMENT.MAKER_PF / DEPARTMENT.CHECKER_PF
-- =============================================================================

SET DEFINE OFF;

-- ---------- Sample PFs (change if your bank uses different IDs) ----------
-- Maker  : 600110, 600310, 600111
-- Checker: 600221, 600321, 600222
-- Admin  : 100001

-- 1) Ensure APP_USER rows
MERGE INTO APP_USER u
USING (
  SELECT '600110' PF_NO, 'SAMPLE Maker DIT' USER_NAME, 'Maker' DESIGNATION, 'MAKER' ROLE_CODE FROM DUAL
  UNION ALL SELECT '600221', 'SAMPLE Checker DIT', 'Checker', 'CHECKER' FROM DUAL
  UNION ALL SELECT '600310', 'SAMPLE Maker DIGIT', 'Maker', 'MAKER' FROM DUAL
  UNION ALL SELECT '600321', 'SAMPLE Checker DIGIT', 'Checker', 'CHECKER' FROM DUAL
  UNION ALL SELECT '600111', 'SAMPLE Maker TEST', 'Maker', 'MAKER' FROM DUAL
  UNION ALL SELECT '600222', 'SAMPLE Checker TEST', 'Checker', 'CHECKER' FROM DUAL
) src
ON (u.PF_NO = src.PF_NO)
WHEN MATCHED THEN UPDATE SET
  u.IS_ACTIVE = 'Y',
  u.ROLE_CODE = src.ROLE_CODE,
  u.USER_NAME = NVL(u.USER_NAME, src.USER_NAME),
  u.UPDATED_AT = SYSTIMESTAMP,
  u.UPDATED_BY = 'SEED_MC'
WHEN NOT MATCHED THEN INSERT (PF_NO, USER_NAME, DESIGNATION, ROLE_CODE, AD_LOGIN_ID, IS_ACTIVE, CREATED_BY)
VALUES (src.PF_NO, src.USER_NAME, src.DESIGNATION, src.ROLE_CODE, src.PF_NO, 'Y', 'SEED_MC');

-- Admin is SCV config login (ApiKey ADMIN_USER_ID/PWD) — deactivate APP_USER ADMIN rows
UPDATE APP_USER
SET IS_ACTIVE = 'N',
    UPDATED_AT = SYSTIMESTAMP,
    UPDATED_BY = 'SEED_MC'
WHERE UPPER(ROLE_CODE) = 'ADMIN';

-- Point users at DIT dept where helpful
UPDATE APP_USER u
SET DEPT_ID = (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DIT' AND IS_ACTIVE = 'Y' AND ROWNUM = 1),
    UPDATED_AT = SYSTIMESTAMP
WHERE u.PF_NO IN ('600110','600221')
  AND EXISTS (SELECT 1 FROM DEPARTMENT WHERE DEPT_CODE = 'DIT' AND IS_ACTIVE = 'Y');

-- 2) DIT department: no dept-level Maker/Checker (project/section only)
UPDATE DEPARTMENT
SET MAKER_PF = NULL,
    CHECKER_PF = NULL,
    HAS_REVENUE = 'Y',
    IS_ACTIVE = 'Y',
    UPDATED_AT = SYSTIMESTAMP,
    UPDATED_BY = 'SEED_MC'
WHERE DEPT_CODE = 'DIT';

-- 3) DIT Capital — all active projects under DIT
UPDATE PROJECT p
SET MAKER_PF = '600110',
    CHECKER_PF = '600221',
    UPDATED_AT = SYSTIMESTAMP,
    UPDATED_BY = 'SEED_MC'
WHERE p.IS_ACTIVE = 'Y'
  AND EXISTS (
    SELECT 1 FROM SECTION s
    JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
    WHERE s.SECTION_ID = p.SECTION_ID AND d.DEPT_CODE = 'DIT'
  );

-- Optional: second Maker/Checker pair on ONE project (example — Networking first project)
-- UPDATE PROJECT SET MAKER_PF='600310', CHECKER_PF='600321' WHERE PROJECT_ID = <id>;

-- 4) DIT Revenue — sections with revenue Maker/Checker
UPDATE SECTION s
SET MAKER_PF = '600110',
    CHECKER_PF = '600221',
    UPDATED_AT = SYSTIMESTAMP,
    UPDATED_BY = 'SEED_MC'
WHERE s.IS_ACTIVE = 'Y'
  AND EXISTS (
    SELECT 1 FROM DEPARTMENT d
    WHERE d.DEPT_ID = s.DEPT_ID AND d.DEPT_CODE = 'DIT' AND d.HAS_REVENUE = 'Y'
  );

-- 5) Non-DIT departments — department-wise Maker/Checker (capital only)
UPDATE DEPARTMENT
SET MAKER_PF = '600310',
    CHECKER_PF = '600321',
    HAS_REVENUE = 'N',
    UPDATED_AT = SYSTIMESTAMP,
    UPDATED_BY = 'SEED_MC'
WHERE DEPT_CODE = 'DIGIT' AND IS_ACTIVE = 'Y';

UPDATE DEPARTMENT
SET MAKER_PF = '600111',
    CHECKER_PF = '600222',
    HAS_REVENUE = 'N',
    UPDATED_AT = SYSTIMESTAMP,
    UPDATED_BY = 'SEED_MC'
WHERE DEPT_CODE IN ('TEST','TEST 02') AND IS_ACTIVE = 'Y';

-- 6) Ensure non-DIT have a GENERAL section for projects (if missing)
INSERT INTO SECTION (DEPT_ID, SECTION_CODE, SECTION_NAME, IS_ACTIVE, CREATED_AT, CREATED_BY)
SELECT d.DEPT_ID, 'GEN', d.DEPT_NAME || ' — General', 'Y', SYSTIMESTAMP, 'SEED_MC'
FROM DEPARTMENT d
WHERE d.IS_ACTIVE = 'Y'
  AND NVL(d.HAS_REVENUE,'N') = 'N'
  AND UPPER(TRIM(d.DEPT_CODE)) <> 'DIT'
  AND NOT EXISTS (
    SELECT 1 FROM SECTION s WHERE s.DEPT_ID = d.DEPT_ID AND s.IS_ACTIVE = 'Y'
  );

COMMIT;

-- ---------- Verify ----------
SELECT DEPT_CODE, HAS_REVENUE, MAKER_PF, CHECKER_PF FROM DEPARTMENT WHERE IS_ACTIVE='Y' ORDER BY DEPT_CODE;
SELECT p.PROJECT_ID, p.PROJECT_NAME, p.MAKER_PF, p.CHECKER_PF, d.DEPT_CODE
FROM PROJECT p
JOIN SECTION s ON s.SECTION_ID = p.SECTION_ID
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE p.IS_ACTIVE='Y' AND d.DEPT_CODE='DIT';
SELECT s.SECTION_ID, s.SECTION_NAME, s.MAKER_PF, s.CHECKER_PF
FROM SECTION s
JOIN DEPARTMENT d ON d.DEPT_ID = s.DEPT_ID
WHERE d.DEPT_CODE='DIT' AND s.IS_ACTIVE='Y';
SELECT PF_NO, ROLE_CODE, IS_ACTIVE FROM APP_USER
WHERE PF_NO IN ('600110','600221','600310','600321','600111','600222','100001');
